default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  username: root
  host: db
  database: app_development
  password: password

test:
  <<: *default
  username: root
  host: db
  database: app_test
  password: password
