services:
  frontend:
    build:
      context: ./frontend
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
  backend:
    build:
      context: ./backend
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
