services:
  frontend:
    build:
      context: ./frontend
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
    command: npm run dev
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    command: rails server -b 0.0.0.0
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
