source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.5'

gem 'bootsnap', require: false

gem 'pg', '~> 1.1'

gem 'puma', '~> 6.4'

gem 'rails', '~> 7.2.1'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'ostruct'

gem 'rack-cors'

gem 'config'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'
end
