name: Deploy to heroku.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Heroku CLI existence (debug)
        run: |
          which heroku || echo "No heroku in PATH"
          heroku --version || echo "Can't run heroku"

      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./backend
          dockerfile_name: Dockerfile
          docker_options: '--no-cache'
          process_type: web

      - name: Run db:migrate
        run: |
          heroku run rails db:migrate --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
